### ISSUE TITLE
Automated Builds for Nvidia images

### ISSUE THREAD

**Issue by AustinDeric** [ros-industrial/docker#11]
Currently, nvidia docker files need to be build using the command such as:
```nvidia-docker build -t rosindustrial/core-nvidia:kinetic```

The problem is that https://hub.docker.com/r/rosindustrial cannot do this.  Therefore to get images to the repository, i need to build them locally and push to docker hub.

This method is not ideal due to configuration management reasons.  The ideal method would use the automated build method.

**Comment by gavanderhoorn** [comment]
Do those `Dockerfile`s have any special requirements / statements in them that require that?

I'm asking because I seem to remember that `nvidia-docker build ..` is basically a pass-through to the regular `docker build ..`, and at least for the nvidia-enabled images I build in our lab, `nvidia-docker build ..` is not necessary.

The `nvidia-docker` wiki also just uses regular `docker build ..` for their examples: [nvidia-docker/wiki/Testing-the-samples](https://github.com/NVIDIA/nvidia-docker/wiki/Testing-the-samples).

**Comment by AustinDeric** [comment]
@gavanderhoorn is correct, this is a non-issue.
